# Generated by Django 5.1.1 on 2024-09-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingplace',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingplace',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkingplace',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
