# Generated by Django 5.1.1 on 2024-09-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_parkingplace_address_parkingplace_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplace',
            name='address',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='city',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='country',
            field=models.CharField(blank=True, default=2, max_length=100),
            preserve_default=False,
        ),
    ]
