# Generated by Django 5.1.1 on 2024-10-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0005_parkingspace_location_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingspace",
            name="location_name",
        ),
    ]
