# Generated by Django 5.1.1 on 2024-11-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0007_parkingslot_payment_vehicle_parkingbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspace",
            name="location_name",
            field=models.CharField(default="foo", max_length=255),
            preserve_default=False,
        ),
    ]
