# Generated by Django 5.1.1 on 2024-11-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0008_parkingspace_location_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_parking_manager",
            field=models.BooleanField(default=False),
        ),
    ]
