# Generated by Django 5.1.1 on 2024-11-16 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0009_remove_userprofile_is_verified_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingslot",
            name="booked_at",
        ),
        migrations.RemoveField(
            model_name="parkingslot",
            name="released_at",
        ),
        migrations.RemoveField(
            model_name="parkingslot",
            name="user",
        ),
        migrations.AddField(
            model_name="parkingslot",
            name="slot_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
